### PR TITLE
Fix incorrect attribute / Use template-specific version of Lo-dash

### PR DESCRIPTION
**Pull request by shinnn**
- At the current version, `readonly` attribute is mistyped and regarded as `spellcheck=` (See the screenshot below). So I fixed it as a [boolean attribute](http://www.w3.org/TR/html5/infrastructure.html#boolean-attribute).
  
  screenshot 2014-02-05 3 51 19
- I replaced [Underscore.js](http://underscorejs.org/) with the template-specific version of [Lo-dash](http://lodash.com/), which is built with `lodash include="template"` command. (See http://lodash.com/custom-builds for more details about custom build.) It includes only template engine functions and doesn't include unnecessary features.

### CODE REVIEW

**Comment by moznion** [comment]
Nice patch!

Thank you.

**Comment by moznion** [comment]
Do I re-build Lo-dash when it is updated?

**Comment by shinnn** [comment]
Yes. If you want to update it, you should install Node.js and run the following command:

``` shellscript
$ [sudo] npm install -g lodash-cli
$ lodash inclide="template" -o <filename>
```

However, optimizing Lo-Dash is not necessary in this case, because chrome extensions will be installed locally and reducing file size is not important as it is for webapps.
It is mostly subject of _personal_ preference.

If you prefer easier installation and update, you can [directly download](http://lodash.com/#download) the full-featured version of Lo-dash.

**Comment by moznion** [comment]
Thanks :)

**Pull request merged**
